# 谈谈错误处理

## 序

对这个问题感兴趣的原因是 之前一直没有想明白 业务开发中 到底应该如何的进行错误处理, 而且最近 一直写 golang python js, 感受了一下 不同的错误处理模式 和 异步模式下的错误处理方式, 所以比较好奇, 于是提了一个问题 [Try/catch Vs 返回错误类型，这两种异常处理的方式各有什么优缺点？](!https://www.zhihu.com/question/300635800) 看了各位大佬的回答以后, 自己也有一点感悟,这里记一下.

## 错误 VS 异常

首先, 我们应该有一个原则, 我们处理的是错误, 异常要让它抛处理来. 至于怎么区分错误 和 异常呢? 对我本人来说有一个比较感性的原则: _预期内的叫做错误 预期外的叫做异常_ 举个例子:

我有个典型的 web app, 逻辑部分有 controller(业务逻辑) 和 dao, 我的 dao 访问数据库的部分可能抛一些错误, 有的错误类似某个唯一索引重复这种(这里我们叫 UniqueException), 是可以预料到的, 我们应该做一些处理, 而不能任由这个错误导致程序崩溃. 有的类似参数传错, 这种的是不在我们预期内发生的, 就应该让他崩溃, 然后开发人员修改. 所以 典型的代码如下:

```python

def dao_query(conditions):
    try:
        mysql.excute(conditions)
    except UniqueException: #
        # 做一些处理 比如返回 None 或者接着往上抛
    except XXXXXException:
        # 做一些处理 比如返回 None 或者接着往上抛
```

而不能

```python

def dao_query(conditions):
    try:
        mysql.excute(conditions)
    except Exception: #
       #
```

因为这样会把一些本来会导致程序崩溃 需要程序员修改的意料之外的错误也处理掉

有时候一些我们能预料到随机发生的异常, 比如网络抖动这种的, 我们也应该把这种异常作为错误捕获到, 这种机制叫异常捕获, 比如 try...catch (这个既用来处理错误, 也用于底层把异常捕获成错误来处理) 比如 golang 的 panic/recover (golang 中 return 和 if 用来处理错误, panic/recover 用来捕获异常)

我们接下来讨论的都是对错误的处理

## 错误处理模式大比拼

这里就拿我会的几种编程语言, 分析下他们错误处理的模式:

### 值模式

这是一个比较原始且易于理解的模式, 核心思想在于把错误当做一个值, 和正常的值一起处理, 典型的就是 c 语言和 golang, 这种模式处理错误的核心机制就是对正常值处理的 if/return 组合. golang 和 c 语言的区别基本就是一个有没有一个专门的错误类型 c 语言比较喜欢用一个数字代表错误代码, hard code 更多

一个典型的例子, 还是用 web app 来举例:

dao 可以展示捕获异常处理成错误的过程,
controller 是一个典型的业务逻辑的错误处理的过程

```golang

func BookQueryDao(query) ([]Book, err error) {
    // 正常的业务逻辑
    defer func() {
        // 这里捕获异常, 处理成自己的错误类型
        if e := recover(); r != nil {
			if e.Error() == "UNIQUE" {
                err = MyError{
                    msg:"插入重复"
                }
            }
		}
    }

}

```

然后我们在 controller(业务逻辑) 把错误当做一个值来用, 对 **所有** 下层调用的返回值都进行判断, 然后处理

```golang

func BookListController(query) ([]Book, int , err error) {
    // xxx
    books, err := BookQueryDao(query)
    if err != nil {
        return nil , 0 ,err
    }

    persions, err := PersionQueryDao(query)
    if err != nil {
        if err.msg == "插入重复" {
            // 一些逻辑
        }
        return nil , 0 ,err
    }
}
```

这个模式, 也决定了他是一个我个人认为很不优雅的错误处理方法, 不优雅主要体现在:

1. 在 _业务逻辑_ 中 错误处理的逻辑 和 正常的逻辑混在一起, 降低代码的可读性
2. 反不反回, 处不处理 error 全靠自觉, 有时候偷懒一下, 写个 books,_ = BookQueryDao() 就不处理了, 导致了不可预料的错误, 所以一般要求严禁对错误类型进行_

### 单独错误栈

这种模式, 就是我们最常用的 try....catch... 模式, 他最大的优点在于, 把错误和正常的值分开, 这个最大的好处就是把 错误处理的逻辑和正常的逻辑分开, 还是 web app 的 例子:

dao 层 区别不大, 换一种写法而已, 主要还是把我们期待的异常捕获成错误,

```python
def dao_query(conditions):
    try:
        mysql.excute(conditions)
    except UniqueException: #
        raise MyException()
```

主要区别在于 controller, 神清气爽了有木有, 普通的逻辑和错误逻辑分开了有木有, 普通逻辑正常进行, 当出错了转到正常的逻辑来处理, 清晰感觉

```python
def controller_list(conditions):
    try:
        a = dao_query1(conditions)
        b = dao_query2(conditions)
    except MyException as e: #
        # 异常处理的逻辑 像 回滚 关闭资源
        raise e
```

这种模式也有一些要求:

1. 不能 except Excetion 这种, 会吧异常和错误都处理, 毫无意义
2. 要知道底层会 raise 什么样的错误, 不然会漏掉, 不过这个倒是也有一个好的解决方法, 随后在业务使用章节中会讲

### 异步的错误处理

这时候我们讨论的主要是同步的错误处理模式, 可是现在好多程序都是异步的逻辑, 这时候错误处理怎么办呢?

异步有俩种, 一种是比较麻烦的回调风格, 典型的 js 的 promise, 这个错误处理的方式和 try....catch 有异曲同工之处. 都是把错误处理单独一个栈 只不过用的当出现错误进入不同的函数这种形式来表达.

```js
axios
  .get("/api/xxx")
  .then(res => {
    // 正常的业务逻辑
  })
  .catch(error => {
    if (error == xxxx) {
      //处理
      return null;
    } else {
      reject(error);
    }
  });
```

整体来讲 还不错, 只不过和同步的错误处理方案相对独立, 所以还有一个协程方案:

```python

try:
    await dao_query1()
except MyException as e: #
    # 一些错误
```

这样基本和同步的代码处理起来一样了

## 业务逻辑中的错误处理

关于在业务逻辑中进行错误处理, 我这里也有一个比较不错的实践, 可以给大家参考一下.

首先, 这个问题的本质, 就是处理好, 三个系统的关系, 这三个系统是, 调用我们的系统, 我们的系统, 我们调用的系统. 举个典型的例子, 还是 web app , **我们的系统**就是后端, **调用我们**的是前端, **我们调用**的是数据库.

核心的思想如下, **我们的系统** 有一套统一的错误类型, 包括一个**我们的错误基类**和他的派生类, 我们只 except 这个错误基类, 根据不同派生类的类型进行不同的处理, **我们调用**的系统的错误进入到我们的系统, 一律*捕获*转换成 **我们的错误基类**和他的派生. 然后最后把我们的错误, 转换成 **调用我们** 能理解的形式

拿 web app 来说:

我么一般有一个错误基类

```python
class MyBusinessException(Excetion):
    def __init__(self, code, msg):
        self.code = code # 返回的http code
        self.msg = msg # 返回的错误信息
```

dao 里捕获**我们调用**的成为错误:

```python
def dao_query(conditions):
    try:
        mysql.excute(conditions)
    except UniqueException: #
        raise MyBusinessException(code=500, msg="插入重复")
```

controller 根据错误 进行 回滚 关资源 并且向上抛

```python
def controller_list(conditions):
    try:
        a = dao_query1(conditions)
        b = dao_query2(conditions)
    except MyBusinessException as e: #
        # 异常处理的逻辑 像 回滚 关闭资源
        raise e
```

handler 把错误处理成 **调用我们** 的系统可以理解的形式, 比如这里调用我们的是前端, 就跟他处理成带错误码的 http 响应

```python
def handler_list(conditions):
    try:
        res = controller_list()
        return {
            "books": res
        }
    except MyBusinessException as e: #
        # 异常处理的逻辑 像 回滚 关闭资源
        return {
            "code": e.code,
            "msg" :e.msg
        }
```

## 尾巴

以上的部分只是一些平常开发的一些体会, 最佳实践的寻找本身就是一件痛苦且费力的事情, 希望本文能给你们提供一些帮助, 有更好的实践也欢迎交流.

(最近对 rust 的错误处理模式比较感兴趣, 有时间补上

(最近感觉写字比较吃力,写出来的句子不通顺, 抽时间会开个专栏写写议论文练一下
